name: Deploy to GitHub Pages

permissions:
  contents: write
on:
  push:
    branches:
      - main  # Change 'main' to your default branch if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Adjust as needed

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Create gh-pages branch if it doesn't exist
        run: |
          git branch -f gh-pages
      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          mv dist dist_tmp      
          git checkout gh-pages
          git reset --hard main
          mv dist_tmp dist      
          git add -f dist
          git commit -m 'Deployment'
          git push --force origin gh-pages
  