name: Deploy to GitHub Pages

permissions:
  contents: write
on:
  push:
    branches:
      - main  # Change 'main' to your default branch if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Adjust as needed

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Create gh-pages branch if it doesn't exist
        run: |
          git branch -f gh-pages
      - name: Deploy to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Fetch remote gh-pages branch and rebase/merge
          git fetch origin gh-pages
          git checkout gh-pages
          git merge origin/gh-pages --allow-unrelated-histories
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git push origin gh-pages
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git reset --hard
  
          # Copy the build output to the gh-pages branch
          #cp -r dist/* dist
          git add -f dist
          git commit -m "Deploy to GitHub Pages"
  
          # Push to gh-pages branch
          git push origin gh-pages --force          
